name: 'Deploy Release Candidate'

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "README.md"

jobs:
  deploy-rc:
    runs-on: ubuntu-latest
    env:
      wallet_canister_id: zo2gr-xaaaa-aaaar-qaqyq-cai
      # Needed to surpass dfx error to use the insecure plaintext identity
      DFX_WARNING: -mainnet_plaintext_identity
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Install dfx'
        uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365
        with:
          dfx-version: "0.25.0"

      - name: 'Confirm dfx successful installation'
        run: dfx --version

      - name: "Import dfx deploy key"
        env:
          DFX_DEPLOY_KEY: ${{ secrets.DFX_DEPLOY_KEY }}
        run: |
          key_pem=$(mktemp)
          printenv "DFX_DEPLOY_KEY" > "$key_pem"
          dfx identity import --storage-mode plaintext ci "$key_pem"
          rm "$key_pem"
          dfx identity use ci
          dfx identity get-principal
          dfx identity set-wallet --ic --force "${{ env.wallet_canister_id }}"
          dfx wallet balance --ic