name: 'Deploy_Release_Candidate'

on: workflow_dispatch

jobs:
  deploy-rc:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install dfx'
        uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365
        with:
          dfx-version: "0.25.0"
      - name: 'Confirm successful installation'
        run: dfx --version