name: Release

on:
  workflow_dispatch

jobs:
  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install release-plz from fork
        run: |
          git clone https://github.com/lpahlavi/release-plz.git /tmp/release-plz-fork
          cd /tmp/release-plz-fork
          git checkout 9b511999ed04cc5070fe5efcd5481b6b2cc035c1
          cargo +nightly install --path crates/release_plz
      - name: Run release-plz
        run: release-plz release-pr --git-token ${{ secrets.GITHUB_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
